name: drawing_animation
description: An dart-only library for gradually painting SVG path objects on canvas (drawing line animation).
version: 1.0.0
repository: https://github.com/biocarl/drawing_animation
homepage: https://twitter.com/cahaucks

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.3.0
  path_parsing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.6
  mockito: ^5.3.2

dependency_overrides:
  # test_api: 0.4.14